import { context } from "@actions/github";
import { FileDiff } from "./diff";
import { AIComment, PullRequestSummary } from "./prompts";
import { Context } from "@actions/github/lib/context";
import config from "./config";

export const OVERVIEW_MESSAGE_SIGNATURE =
  "\n<!-- prreview.ai: overview message -->";

export const COMMENT_SIGNATURE = "\n<!-- prreview.ai: comment -->";

export const PAYLOAD_TAG_OPEN = "\n<!-- prreview.ai: payload --";
export const PAYLOAD_TAG_CLOSE = "\n-- prreview.ai: payload -->";

const PR_REVIEW_AI_SIGNATURE = "--- \n_autogenerated by [Semgrep Static PR Review](https://github.com/thallesasv/pullRequestCodeReview)_";

function formatCommentLabel(label: string): string {
  const normalizedLabel = label.trim().toLowerCase();

  const labelTranslations: Record<string, string> = {
    security: "segurança",
    "possible bug": "possível bug",
    "possible issue": "possível problema",
    performance: "desempenho",
    enhancement: "melhoria",
    "best practice": "melhor prática",
    maintainability: "manutenibilidade",
    readability: "legibilidade",
    typo: "erro de digitação",
    bug: "bug",
    style: "estilo",
    documentation: "documentação",
    tests: "testes",
    refactor: "refatoração",
  };

  return labelTranslations[normalizedLabel] ?? label;
}

function getCommitUrl(
  serverUrl: string,
  owner: string,
  repo: string,
  sha: string
): string {
  // Remove trailing slash if present
  const baseUrl = serverUrl.endsWith("/") ? serverUrl.slice(0, -1) : serverUrl;
  return `${baseUrl}/${owner}/${repo}/commit/${sha}`;
}

export function buildLoadingMessage(
  baseCommit: string,
  commits: {
    sha: string;
    commit: {
      message: string;
    };
  }[],
  fileDiffs: FileDiff[]
): string {
  const { owner, repo } = context.repo;

  let message = `⏳ **Analisando alteracoes neste PR...** ⏳\n\n`;
  message += `_Isso pode levar alguns minutos, por favor aguarde_\n\n`;

  // Group files by operation
  message += `<details>\n<summary>📥 Commits</summary>\n\n`;
  message += `Analisando alteracoes da base (\`${baseCommit.slice(
    0,
    7
  )}\`) até o commit mais recente (\`${commits[commits.length - 1].sha.slice(
    0,
    7
  )}\`):\n`;

  for (const commit of commits.reverse()) {
    message += `- [${commit.sha.slice(0, 7)}](${getCommitUrl(
      config.githubServerUrl,
      owner,
      repo,
      commit.sha
    )}): ${commit.commit.message}\n`;
  }

  message += "\n\n</details>\n\n";

  message += `<details>\n<summary>📁 Arquivos sendo considerados (${fileDiffs.length})</summary>\n\n`;
  for (const diff of fileDiffs) {
    let prefix = "🔄"; // Modified
    if (diff.status === "added") prefix = "➕";
    if (diff.status === "removed") prefix = "➖";
    if (diff.status === "renamed") prefix = "📝";

    let fileText = `${prefix} ${diff.filename}`;
    if (diff.status === "renamed") {
      fileText += ` (de ${diff.previous_filename})`;
    }
    fileText += ` _(${diff.hunks.length} ${
      diff.hunks.length === 1 ? "trecho" : "trechos"
    })_`;
    message += `${fileText}\n`;
  }
  message += "\n</details>\n\n";

  message += PR_REVIEW_AI_SIGNATURE;
  message += OVERVIEW_MESSAGE_SIGNATURE;

  return message;
}

export function buildOverviewMessage(
  summary: PullRequestSummary,
  commits: string[]
): string {
  let message = `## Resumo do PR\n\n`;

  // Add description with proper spacing
  message += `${summary.description.trim()}\n\n`;

  message += `### Alteracoes\n\n`;

  // Create table with proper column alignment and escaping
  message += `| Arquivo | Resumo |\n`;
  message += `|:----------|:---------------|\n`; // Left-align columns

  for (const file of summary.files) {
    // Escape pipes and wrap paths in backticks for better formatting
    const escapedPath = file.filename.replace(/\|/g, "\\|");
    const escapedSummary = file.summary.replace(/\|/g, "\\|");

    message += `| \`${escapedPath}\` | ${escapedSummary} |\n`;
  }

  const payload = {
    commits: commits,
  };

  message += PR_REVIEW_AI_SIGNATURE;
  message += OVERVIEW_MESSAGE_SIGNATURE;
  message += PAYLOAD_TAG_OPEN;
  message += JSON.stringify(payload);
  message += PAYLOAD_TAG_CLOSE;

  return message;
}

export function buildReviewSummary(
  context: Context,
  files: FileDiff[],
  commits: {
    sha: string;
    commit: {
      message: string;
    };
  }[],
  actionableComments: AIComment[],
  skippedComments: AIComment[]
) {
  const { owner, repo } = context.repo;

  let body = "";
  if (actionableComments.length === 0) {
    body += `✅ **Me avise caso precise de ajuda!**\n\n`;
  } else {
    body += `🚨 **Pull request precisa de atenção.**\n\n`;
  }

  body += "### Resumo do Code Review\n\n";

  // Commits section
  body += `<details>\n<summary>Commits Considerados (${commits.length})</summary>\n\n`;
  for (const commit of commits) {
    body += `- [${commit.sha.slice(0, 7)}](${getCommitUrl(
      config.githubServerUrl,
      owner,
      repo,
      commit.sha
    )}): ${commit.commit.message}\n`;
  }
  body += "\n</details>\n\n";

  // Files section
  body += `<details>\n<summary>Arquivos analisados (${files.length})</summary>\n\n`;
  for (const diff of files) {
    let fileText = `- ${diff.filename}`;
    if (diff.status === "renamed") {
      fileText += ` (de ${diff.previous_filename})`;
    }
    fileText += ` _(${diff.hunks.length} ${
      diff.hunks.length === 1 ? "trecho" : "trechos"
    })_`;
    body += `${fileText}\n`;
  }
  body += "\n</details>\n\n";

  // Actionable comments section
  body += `<details>\n<summary>Pontos de Ação (${actionableComments.length})</summary>\n\n`;
  for (const comment of actionableComments) {
    body += `- <details>\n`;
    body += `  <summary>${comment.file} [${comment.start_line}-${comment.end_line}]</summary>\n\n`;
    body += `  > ${formatCommentLabel(comment.label)}: "${comment.header}"\n`;
    body += `  </details>\n`;
  }
  body += "\n</details>\n\n";

  // Skipped comments section
  body += `<details>\n<summary>Comentários Ignorados (${skippedComments.length})</summary>\n\n`;
  for (const comment of skippedComments) {
    body += `- <details>\n`;
    body += `  <summary>${comment.file} [${comment.start_line}-${comment.end_line}]</summary>\n\n`;
    body += `  > ${formatCommentLabel(comment.label)}: "${comment.header}"\n`;
    body += `  </details>\n`;
  }
  body += "</details>\n\n";

  return body;
}
